### ISSUE TITLE
For OCP 4.11+ Netbindservice is needed when creating the deployment

### ISSUE THREAD

**Issue by odellem** [microsoft/sqlworkshops-sqlonopenshift#12]
After OCP 4.10 the policy to give NET_BIND_SERVICE by default is disabled and it needs to be manually added. This piece of yaml should be added to the deployment file to work on OCP 4.11+ clusters.
```
spec:
    template:
        spec:
            containers:
                securityContext:
                    capabilities:
                        add:
                            - NET_BIND_SERVICE
```
